USE PracticeDB;

SELECT
	name AS [Column List]
FROM sys.tables;

--How many customers are from each country?
SELECT
	Country,
	count(CustomerID) AS [Number of Customers]
FROM
	Customers
GROUP BY
	Country
ORDER BY
	[Number of Customers] DESC;


--How many orders has each customer placed?
SELECT
	c.CustomerID AS [ID],
	c.CompanyName AS [Customer],
	COUNT(o.OrderID) As [Number of Orders]
FROM Customers c
LEFT JOIN Orders o
	ON c.CustomerID = o.CustomerID
GROUP BY
	c.CustomerID,
	c.CompanyName
ORDER BY
	[Number of Orders] DESC;

--Which customers have the highest average order value?
SELECT * FROM Customers;
SELECT * FROM Orders;
SELECT * FROM [Order Details];

SELECT
	c.CustomerID AS ID,
	c.CompanyName AS Customer,
	AVG([Order Value]) AS [AVG]
FROM
	Customers c
INNER JOIN Orders o
	ON o.CustomerID = c.CustomerID
INNER JOIN (
	SELECT OrderID, SUM(UnitPrice*Quantity) [Order Value]
	FROM [Order Details]
	GROUP BY OrderID
	) od
	ON o.OrderID = od.OrderID
GROUP BY
	c.CustomerID, c.CompanyName
ORDER BY
	[AVG] DESC;

--What is the total revenue generated by each product?

SELECT
	p.ProductID,
	p.ProductName,
	SUM(od.UnitPrice*od.Quantity) AS [Total Revenue]
FROM Products p
LEFT JOIN [Order Details] od
	ON od.ProductID = p.ProductID
GROUP BY
	p.ProductID,
	p.ProductName
ORDER BY
	[Total Revenue] DESC;

--Which products were sold fewer than 20 times in each year? 

SELECT
	YEAR(O.OrderDate) AS [Year],
	p.ProductID,
	p.ProductName,
	SUM(od.Quantity) AS [Quantity <20]
FROM
	Products p
INNER JOIN [Order Details] od
	ON p.ProductID = od.ProductID
INNER JOIN Orders o
	ON o.OrderID = od.OrderID
GROUP BY
	p.ProductID,
	p.ProductName,
	YEAR(o.OrderDate)
HAVING
	SUM(od.Quantity)< 20
ORDER BY
	 [Year],
	 [Quantity <20] DESC;


--Which product categories generate the highest total revenue?
SELECT * FROM Categories;
SELECT * FROM Products;
SELECT * FROM [Order Details];

SELECT TOP 1
	c.CategoryName AS [Category],
	SUM(od.UnitPrice*od.Quantity) AS [Total Revenue]
FROM
	Categories c
LEFT JOIN Products p
	ON p.CategoryID = c.CategoryID
INNER JOIN [Order Details] od
	on p.ProductID = od.ProductID
GROUP BY
	c.CategoryName
ORDER BY
	[Total Revenue] DESC;

--What are the top three highest-revenue products in each country/region?
WITH ProductRevenue AS(
	SELECT
		o.ShipCountry AS [Country],
		p.ProductName AS [Product],
		SUM(od.UnitPrice*od.Quantity) AS [Total Revenue]
	FROM
		Products p
	INNER JOIN [Order Details] od
		ON p.ProductID = od.ProductID
	INNER JOIN Orders o
		ON o.OrderID = od.OrderID
	GROUP BY
		o.ShipCountry,
		p.ProductName),

RankProducts AS(
	SELECT *,
		RANK() OVER(
			PARTITION BY Country
			ORDER BY [Total Revenue] DESC) AS [Rank by Revenue]
	FROM 
		ProductRevenue)

SELECT
	*
FROM
	RankProducts rp
WHERE
	rp.[Rank by Revenue]
		IN (1,2,3);

--What is the monthly sales revenue trend over time? 

SELECT
	DATENAME(Month, o.OrderDate) AS [Month],
	SUM(od.UnitPrice*od.Quantity) AS [Revenue]
FROM
	Orders o
INNER JOIN [Order Details] od
	ON o.OrderID = od.OrderID
GROUP BY
	DATENAME(Month, o.OrderDate)
ORDER BY
	[Revenue] DESC;

--What is the top-selling product in each category based on total quantity sold?

WITH TopSellingProduct AS(
	SELECT 
		c.CategoryName AS [Category],
		p.ProductName AS [Product],
		SUM(Quantity) AS [Quantity]
	FROM Categories c
	INNER JOIN Products p
		ON c.CategoryID = p.CategoryID
	INNER JOIN [Order Details] od
		ON od.ProductID = p.ProductID
	GROUP BY
		c.CategoryName,
		p.ProductName),

RankProduct AS(
	SELECT *,
	RANK() OVER(
			PARTITION BY [Category]
			ORDER BY [Quantity] DESC) AS [Rank]
	FROM TopSellingProduct
	)

SELECT
	*
FROM
	RankProduct rp
WHERE
	rp.Rank = 1;

--Which customers placed orders only in the first year of operations?
WITH FirstYear AS(
    SELECT
		MIN(YEAR(OrderDate)) AS FirstYear
    FROM
		Orders),

CustomerYears AS(
    SELECT 
        c.CustomerID,
        c.CompanyName,
        YEAR(o.OrderDate) AS OrderYear
    FROM
		Customers c
    INNER JOIN Orders o
        ON c.CustomerID = o.CustomerID)

SELECT
	cy.CompanyName
FROM
	CustomerYears cy
JOIN FirstYear fy
    ON cy.OrderYear = fy.FirstYear
GROUP BY
	cy.CustomerID,
	cy.CompanyName
HAVING 
    COUNT(DISTINCT cy.OrderYear) = 1;

